# Generated by Django 5.0.3 on 2024-04-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session_year_id',
        ),
        migrations.DeleteModel(
            name='Session_Year',
        ),
    ]
