# Generated by Django 5.0.3 on 2024-05-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customuser_user_type_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='Course description'),
        ),
        migrations.AddField(
            model_name='student',
            name='committee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.committee'),
        ),
    ]
